spring.application.name=paiement-service
spring.datasource.url=jdbc:h2:mem:default
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server.port=8084
spring.config.import=optional:configserver:http://localhost:8888/