spring.application.name=Gateway-service
server.port=8080
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.server.webflux.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true


management.endpoints.web.exposure.include=gateway
management.endpoints.access.default=unrestricted

eureka.client.service-url.defaultZone=http://localhost:8761/eureka