spring.application.name=ConfigServer
server.port=8888
spring.cloud.config.server.git.uri=file:///C:/configrepoo
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.refresh-rate=20